[package]
name = "massa_xtask"
version = "2.4.0"
edition = "2021"

[dependencies]
massa_models = {workspace = true}
toml_edit = {workspace = true}   # BOM UPGRADE     Revert to "0.19.8" if problem
walkdir = {workspace = true}
